print("     /|")
print("    / |")
print("   /  |")
print("  /   |")
print(" /    |")
print("/_____|")
print(" _________")
print("|         |")
print("|         |")
print("|         |")
print("|_________|")
print("    /\ ")
print("   /  \ ")
print("  /    \ ")
print(" /      \ ")
print(" \      / ")
print("  \    / ")
print("   \  / ")
print("    \/ ")